#
title: LugZe blog
email: info@lugze.org
description: > # this means to ignore newlines until "baseurl:"
  Linux User Group of Zenica
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://lugze.org"
github_username:  lugze

# Build settings

## Permalink
permalink: /:categories/:year/:title.html

## Markdown

markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
